import React, { useState } from 'react'
import {
  View,
  Text,
  TextInput,
  Alert,
  Modal,
  TouchableOpacity,
  Button,
  ScrollView,
} from 'react-native'
import { Picker } from '@react-native-picker/picker'
import { db, auth } from '../firebase' // Firestore and Auth

const GoalPage = () => {
  const [manualCalories, setManualCalories] = useState('')
  const [manualProtein, setManualProtein] = useState('')
  const [manualFat, setManualFat] = useState('')
  const [manualCarbs, setManualCarbs] = useState('')

  const [autoGenerated, setAutoGenerated] = useState(false) // Toggle for auto-generated macros
  const [modalVisible, setModalVisible] = useState(false) // Modal visibility state
  const [step, setStep] = useState(1) // Step for auto-generation flow

  // States for the auto-generation process
  const [workoutFrequency, setWorkoutFrequency] = useState(null)
  const [height, setHeight] = useState('170')
  const [weight, setWeight] = useState('70')
  const [goalType, setGoalType] = useState(null)
  const [currentWeight, setCurrentWeight] = useState('')
  const [goalWeight, setGoalWeight] = useState('')

  const nextStep = () => setStep(step + 1)
  const prevStep = () => setStep(step - 1)

  // Final calculation logic based on inputs
  const generateMacros = () => {
    let baseCalories = 2000
    let caloriesAdjustment = 0

    switch (workoutFrequency) {
      case '1-2':
        caloriesAdjustment = 200
        break
      case '3-5':
        caloriesAdjustment = 400
        break
      case '6-7':
        caloriesAdjustment = 600
        break
    }

    baseCalories += caloriesAdjustment

    if (goalType === 'lose') {
      baseCalories -= 500
    } else if (goalType === 'gain') {
      baseCalories += 500
    }

    const calculatedProtein = parseInt(weight) * 2
    const calculatedFat = (baseCalories * 0.25) / 9
    const calculatedCarbs =
      (baseCalories - (calculatedProtein * 4 + calculatedFat * 9)) / 4

    // Update the boxes with generated values
    setManualCalories(baseCalories.toString())
    setManualProtein(Math.round(calculatedProtein).toString())
    setManualFat(Math.round(calculatedFat).toString())
    setManualCarbs(Math.round(calculatedCarbs).toString())

    setAutoGenerated(true) // Mark as auto-generated
    setModalVisible(false) // Close the modal
    setStep(1) // Reset step
    Alert.alert('Success', 'Your goals have been updated.')
  }

  // Save macros to Firestore
  const saveGoals = async () => {
    const currentUser = auth.currentUser
    if (!currentUser) {
      Alert.alert('Error', 'No user is logged in.')
      return
    }

    const userId = currentUser.uid

    try {
      await db
        .collection('users')
        .doc(userId)
        .collection('goals')
        .doc('nutrition')
        .set({
          calories: parseInt(manualCalories),
          protein: parseInt(manualProtein),
          fat: parseInt(manualFat),
          carbohydrates: parseInt(manualCarbs),
        })

      Alert.alert('Success', 'Goals saved successfully!')
    } catch (error) {
      console.error(error)
      Alert.alert('Error', 'Failed to save goals.')
    }
  }

  return (
    <View className="flex-1 bg-white p-4">
      <Text className="text-2xl font-bold text-center mb-6">
        Set Your Goals
      </Text>

      {/* Editable Boxes for Manual Input */}
      <View className="mb-4">
        <Text className="text-lg mb-2">Calorie Goal</Text>
        <TextInput
          placeholder="Calories"
          value={manualCalories}
          onChangeText={setManualCalories}
          keyboardType="numeric"
          editable={!autoGenerated}
          className="border border-gray-300 rounded-lg px-4 py-3 text-lg"
        />
      </View>

      <View className="mb-4">
        <Text className="text-lg mb-2">Protein Goal (g)</Text>
        <TextInput
          placeholder="Protein (g)"
          value={manualProtein}
          onChangeText={setManualProtein}
          keyboardType="numeric"
          editable={!autoGenerated}
          className="border border-gray-300 rounded-lg px-4 py-3 text-lg"
        />
      </View>

      <View className="mb-4">
        <Text className="text-lg mb-2">Fat Goal (g)</Text>
        <TextInput
          placeholder="Fat (g)"
          value={manualFat}
          onChangeText={setManualFat}
          keyboardType="numeric"
          editable={!autoGenerated}
          className="border border-gray-300 rounded-lg px-4 py-3 text-lg"
        />
      </View>

      <View className="mb-6">
        <Text className="text-lg mb-2">Carbohydrates Goal (g)</Text>
        <TextInput
          placeholder="Carbohydrates (g)"
          value={manualCarbs}
          onChangeText={setManualCarbs}
          keyboardType="numeric"
          editable={!autoGenerated}
          className="border border-gray-300 rounded-lg px-4 py-3 text-lg"
        />
      </View>

      <Button title="Save Goals" onPress={saveGoals} color="green" />

      <View className="mt-4">
        <Button
          title="Auto Generate Goals"
          onPress={() => setModalVisible(true)}
          color="blue"
          disabled={autoGenerated}
        />
      </View>

      {/* Modal for Auto-Generate Flow */}
      <Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={() => {
          setModalVisible(false)
          setStep(1) // Reset steps if modal is closed
        }}
      >
        <View className="flex-1 justify-end bg-black bg-opacity-50">
          <View className="bg-white rounded-t-2xl p-6">
            {/* Close Modal Button */}
            <TouchableOpacity
              className="absolute top-4 right-4"
              onPress={() => {
                setModalVisible(false)
                setStep(1)
              }}
            >
              <Text className="text-xl font-bold">×</Text>
            </TouchableOpacity>

            <ScrollView>
              {/* Steps UI */}
              {step === 1 && (
                <View>
                  <Text className="text-xl font-bold mb-4 text-center">
                    How many times a week do you work out?
                  </Text>
                  <Button
                    title="1-2 times"
                    onPress={() => setWorkoutFrequency('1-2')}
                    color={workoutFrequency === '1-2' ? 'green' : 'gray'}
                  />
                  <Button
                    title="3-5 times"
                    onPress={() => setWorkoutFrequency('3-5')}
                    color={workoutFrequency === '3-5' ? 'green' : 'gray'}
                  />
                  <Button
                    title="6-7 times"
                    onPress={() => setWorkoutFrequency('6-7')}
                    color={workoutFrequency === '6-7' ? 'green' : 'gray'}
                  />
                  <Button
                    title="Next"
                    onPress={nextStep}
                    disabled={!workoutFrequency}
                    color="blue"
                  />
                </View>
              )}

              {step === 2 && (
                <View>
                  <Text className="text-xl font-bold mb-4 text-center">
                    Select your height and weight
                  </Text>
                  <View className="flex-row justify-between mb-4">
                    {/* Height Picker */}
                    <View className="w-1/2 pr-2">
                      <Text className="text-lg mb-2">Height (cm)</Text>
                      <Picker selectedValue={height} onValueChange={setHeight}>
                        {[...Array(81)].map((_, i) => (
                          <Picker.Item
                            key={i}
                            label={`${140 + i}`}
                            value={`${140 + i}`}
                          />
                        ))}
                      </Picker>
                    </View>

                    {/* Weight Picker */}
                    <View className="w-1/2 pl-2">
                      <Text className="text-lg mb-2">Weight (kg)</Text>
                      <Picker selectedValue={weight} onValueChange={setWeight}>
                        {[...Array(121)].map((_, i) => (
                          <Picker.Item
                            key={i}
                            label={`${40 + i}`}
                            value={`${40 + i}`}
                          />
                        ))}
                      </Picker>
                    </View>
                  </View>

                  <View className="flex-row justify-between">
                    <Button title="Previous" onPress={prevStep} color="gray" />
                    <Button title="Next" onPress={nextStep} color="blue" />
                  </View>
                </View>
              )}

              {step === 3 && (
                <View>
                  <Text className="text-xl font-bold mb-4 text-center">
                    What is your goal?
                  </Text>
                  <Button
                    title="Lose Weight"
                    onPress={() => setGoalType('lose')}
                    color={goalType === 'lose' ? 'green' : 'gray'}
                  />
                  <Button
                    title="Maintain Weight"
                    onPress={() => setGoalType('maintain')}
                    color={goalType === 'maintain' ? 'green' : 'gray'}
                  />
                  <Button
                    title="Gain Weight"
                    onPress={() => setGoalType('gain')}
                    color={goalType === 'gain' ? 'green' : 'gray'}
                  />
                  <View className="flex-row justify-between">
                    <Button title="Previous" onPress={prevStep} color="gray" />
                    <Button
                      title="Next"
                      onPress={nextStep}
                      disabled={!goalType}
                      color="blue"
                    />
                  </View>
                </View>
              )}

              {step === 4 && (
                <View>
                  <Text className="text-xl font-bold mb-4 text-center">
                    Enter your current weight (kg)
                  </Text>
                  <TextInput
                    placeholder="Current weight"
                    value={currentWeight}
                    onChangeText={setCurrentWeight}
                    keyboardType="numeric"
                    className="border border-gray-300 rounded-lg px-4 py-3 text-lg mb-4"
                  />
                  <View className="flex-row justify-between">
                    <Button title="Previous" onPress={prevStep} color="gray" />
                    <Button
                      title="Next"
                      onPress={nextStep}
                      disabled={!currentWeight}
                      color="blue"
                    />
                  </View>
                </View>
              )}

              {step === 5 && (
                <View>
                  <Text className="text-xl font-bold mb-4 text-center">
                    Enter your goal weight (kg)
                  </Text>
                  <TextInput
                    placeholder="Goal weight"
                    value={goalWeight}
                    onChangeText={setGoalWeight}
                    keyboardType="numeric"
                    className="border border-gray-300 rounded-lg px-4 py-3 text-lg mb-4"
                  />
                  <View className="flex-row justify-between">
                    <Button title="Previous" onPress={prevStep} color="gray" />
                    <Button
                      title="Generate Goals"
                      onPress={generateMacros}
                      disabled={!goalWeight}
                      color="green"
                    />
                  </View>
                </View>
              )}
            </ScrollView>
          </View>
        </View>
      </Modal>
    </View>
  )
}

export default GoalPage
